#!/usr/bin/python3

# SPDX-FileCopyrightText: 2024 Kenta Hirachi
# SPDX-License=Identifier: BSD-3-Clause

import sys
import random

def main():

    
    rolls = int(sys.stdin.read().strip()) 

    if rolls <= 0:
            print("0以上の数字を入力してください。")
            return
    total = 0
    results = []
    for i in range(rolls):
        result = random.randint(1, 6)
        results.append(f"{result}")
        total += result
    
    print(f"{' '.join(results)} 合計値: {total}")
    #for j in range(0, len(results), 10):
    #print(" ".join(results[j:j+10]))

if __name__ == "__main__":
    main()
