#!/usr/bin/python3
# SPDX-FileCopyrightText: 2024 Kenta Hirachi


import sys


def tonum(s):
    try:
        return int(line)
    except:
        return float(line)


for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)

