#!/usr/bin/python3
import sys


def tonum(s):
    try:
        return int(line)
    except:
        return float(line)


for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)

